import { AuditLog, UserRole } from '../types';
import { apiRequest } from './api';
export interface LogActionParams { userId:string;userName:string;role:UserRole;action:string;resource:string;resourceId:string;status?:'success'|'warning'|'failed';ipAddress?:string; }
export const auditService = {
  getLogs: (filterAction?:string) => apiRequest<AuditLog[]>(`/audit-logs${filterAction&&filterAction!=='all'?`?action=${encodeURIComponent(filterAction)}`:''}`),
  logAction: async (_params:LogActionParams) => { throw new Error('Audit logs are generated by the backend'); },
};
